export const BIBLE_BOOKS = [
  { english: "Genesis", tamil: "ஆதியாகமம்", chapters: 50 },
  { english: "Exodus", tamil: "யாத்திராகமம்", chapters: 40 },
  { english: "Leviticus", tamil: "லேவியராகமம்", chapters: 27 },
  { english: "Numbers", tamil: "எண்ணாகமம்", chapters: 36 },
  { english: "Deuteronomy", tamil: "உபாகமம்", chapters: 34 },
  { english: "Joshua", tamil: "யோசுவா", chapters: 24 },
  { english: "Judges", tamil: "நியாயாதிபதிகள்", chapters: 21 },
  { english: "Ruth", tamil: "ரூத்", chapters: 4 },
  { english: "1 Samuel", tamil: "1 சாமுவேல்", chapters: 31 },
  { english: "2 Samuel", tamil: "2 சாமுவேல்", chapters: 24 },
  { english: "1 Kings", tamil: "1 இராஜாக்கள்", chapters: 22 },
  { english: "2 Kings", tamil: "2 இராஜாக்கள்", chapters: 25 },
  { english: "1 Chronicles", tamil: "1 நாளாகமம்", chapters: 29 },
  { english: "2 Chronicles", tamil: "2 நாளாகமம்", chapters: 36 },
  { english: "Ezra", tamil: "எஸ்றா", chapters: 10 },
  { english: "Nehemiah", tamil: "நெகேமியா", chapters: 13 },
  { english: "Esther", tamil: "எஸ்தர்", chapters: 10 },
  { english: "Job", tamil: "யோபு", chapters: 42 },
  { english: "Psalms", tamil: "சங்கீதம்", chapters: 150 },
  { english: "Proverbs", tamil: "நீதிமொழிகள்", chapters: 31 },
  { english: "Ecclesiastes", tamil: "பிரசங்கி", chapters: 12 },
  { english: "Song of Solomon", tamil: "உன்னதப்பாட்டு", chapters: 8 },
  { english: "Isaiah", tamil: "ஏசாயா", chapters: 66 },
  { english: "Jeremiah", tamil: "எரேமியா", chapters: 52 },
  { english: "Lamentations", tamil: "புலம்பல்", chapters: 5 },
  { english: "Ezekiel", tamil: "எசேக்கியேல்", chapters: 48 },
  { english: "Daniel", tamil: "தானியேல்", chapters: 12 },
  { english: "Hosea", tamil: "ஓசியா", chapters: 14 },
  { english: "Joel", tamil: "யோவேல்", chapters: 3 },
  { english: "Amos", tamil: "ஆமோஸ்", chapters: 9 },
  { english: "Obadiah", tamil: "ஒபதியா", chapters: 1 },
  { english: "Jonah", tamil: "யோனா", chapters: 4 },
  { english: "Micah", tamil: "மீகா", chapters: 7 },
  { english: "Nahum", tamil: "நாகூம்", chapters: 3 },
  { english: "Habakkuk", tamil: "ஆபகூக்", chapters: 3 },
  { english: "Zephaniah", tamil: "செப்பனியா", chapters: 3 },
  { english: "Haggai", tamil: "ஆகாய்", chapters: 2 },
  { english: "Zechariah", tamil: "சகரியா", chapters: 14 },
  { english: "Malachi", tamil: "மல்கியா", chapters: 4 },
  { english: "Matthew", tamil: "மத்தேயு", chapters: 28 },
  { english: "Mark", tamil: "மாற்கு", chapters: 16 },
  { english: "Luke", tamil: "லூக்கா", chapters: 24 },
  { english: "John", tamil: "யோவான்", chapters: 21 },
  { english: "Acts", tamil: "அப்போஸ்தலர்", chapters: 28 },
  { english: "Romans", tamil: "ரோமர்", chapters: 16 },
  { english: "1 Corinthians", tamil: "1 கொரிந்தியர்", chapters: 16 },
  { english: "2 Corinthians", tamil: "2 கொரிந்தியர்", chapters: 13 },
  { english: "Galatians", tamil: "கலாத்தியர்", chapters: 6 },
  { english: "Ephesians", tamil: "எபேசியர்", chapters: 6 },
  { english: "Philippians", tamil: "பிலிப்பியர்", chapters: 4 },
  { english: "Colossians", tamil: "கொலோசெயர்", chapters: 4 },
  { english: "1 Thessalonians", tamil: "1 தெசலோனிக்கேயர்", chapters: 5 },
  { english: "2 Thessalonians", tamil: "2 தெசலோனிக்கேயர்", chapters: 3 },
  { english: "1 Timothy", tamil: "1 தீமோத்தேயு", chapters: 6 },
  { english: "2 Timothy", tamil: "2 தீமோத்தேயு", chapters: 4 },
  { english: "Titus", tamil: "தீத்து", chapters: 3 },
  { english: "Philemon", tamil: "பிலேமோன்", chapters: 1 },
  { english: "Hebrews", tamil: "எபிரெயர்", chapters: 13 },
  { english: "James", tamil: "யாக்கோபு", chapters: 5 },
  { english: "1 Peter", tamil: "1 பேதுரு", chapters: 5 },
  { english: "2 Peter", tamil: "2 பேதுரு", chapters: 3 },
  { english: "1 John", tamil: "1 யோவான்", chapters: 5 },
  { english: "2 John", tamil: "2 யோவான்", chapters: 1 },
  { english: "3 John", tamil: "3 யோவான்", chapters: 1 },
  { english: "Jude", tamil: "யூதா", chapters: 1 },
  { english: "Revelation", tamil: "வெளிப்படுத்தின விசேஷம்", chapters: 22 }
];
